[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.2"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Isaac Lab Differentiable RL"
author = "Isaac Lab Project Developers"
maintainer = "Isaac Lab Project Developers"
description = "Differentiable direct environment workflows for Isaac Lab"
repository = "https://github.com/isaac-sim/IsaacLab.git"
keywords = ["isaaclab", "diffrl", "differentiable", "reinforcement-learning"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_experimental" = {}
"isaaclab_newton" = {}
"isaaclab_tasks" = {}

[[python.module]]
name = "isaaclab_diffrl"

[isaac_lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"